export const DEMO_ALERTS = [
  {
    id: "demo-1",
    title: "Flu Outbreak",
    description:
      "High rate of viral influenza cases reported in New Delhi. Hospitals dealing with influx.",
    lat: 28.6139,
    lng: 77.209,
    city: "New Delhi",
    state: "Delhi",
    severity: "high",
    radius: 15,
  },
  {
    id: "demo-2",
    title: "Dengue Alert",
    description: "Mosquito-borne viral disease cases rising in Mumbai due to recent rains.",
    lat: 19.076,
    lng: 72.8777,
    city: "Mumbai",
    state: "Maharashtra",
    severity: "medium",
    radius: 12,
  },
  {
    id: "demo-3",
    title: "Malaria Warning",
    description: "Several cases of Malaria reported in Chennai suburbs.",
    lat: 13.0827,
    lng: 80.2707,
    city: "Chennai",
    state: "Tamil Nadu",
    severity: "high",
    radius: 10,
  },
  {
    id: "demo-4",
    title: "Water Contamination",
    description: "Reports of contaminated water supply in parts of Kolkata.",
    lat: 22.5726,
    lng: 88.3639,
    city: "Kolkata",
    state: "West Bengal",
    severity: "low",
    radius: 8,
  },
  {
    id: "demo-5",
    title: "Viral Fever",
    description: "Seasonal viral fever cases increasing in Bangalore office districts.",
    lat: 12.9716,
    lng: 77.5946,
    city: "Bangalore",
    state: "Karnataka",
    severity: "medium",
    radius: 7,
  },
  {
    id: "demo-6",
    title: "Respiratory Issues",
    description: "Air quality related respiratory complaints in Hyderabad.",
    lat: 17.385,
    lng: 78.4867,
    city: "Hyderabad",
    state: "Telangana",
    severity: "low",
    radius: 6,
  },
  {
    id: "demo-7",
    title: "H1N1 Alert",
    description: "Isolated cases of H1N1 reported in Pune.",
    lat: 18.5204,
    lng: 73.8567,
    city: "Pune",
    state: "Maharashtra",
    severity: "high",
    radius: 9,
  },
  {
    id: "demo-8",
    title: "Heat Wave",
    description: "Extreme heat advisory in Ahmedabad. Stay hydrated.",
    lat: 23.0225,
    lng: 72.5714,
    city: "Ahmedabad",
    state: "Gujarat",
    severity: "medium",
    radius: 20,
  },
  {
    id: "demo-9",
    title: "Food Poisoning",
    description: "Cluster of food poisoning cases in Jaipur tourist area.",
    lat: 26.9124,
    lng: 75.7873,
    city: "Jaipur",
    state: "Rajasthan",
    severity: "low",
    radius: 4,
  },
  {
    id: "demo-10",
    title: "Chikungunya",
    description: "Chikungunya cases identified in Lucknow.",
    lat: 26.8467,
    lng: 80.9462,
    city: "Lucknow",
    state: "Uttar Pradesh",
    severity: "high",
    radius: 11,
  },
] as const;
